### ISSUE TITLE
Error with plot_microshades() with R 4.3.0

### ISSUE THREAD

**Issue by sarmol** [KarstensLab/microshades#21]
Hi,
Thank you for developing this very nice package.

I have used microshades with R version 4.1 without problems, but after updating to R 4.3.0, the plot_microshades() function fails with the following message:

Error in is.na(cdf$hex) || is.na(cdf$group) : 
  'length = 29' in coercion to 'logical(1)'

I found by googling that this might be due to changes in R:

https://stackoverflow.com/questions/72848442/r-warning-lengthx-2-1-in-coercion-to-logical1
https://cran.r-project.org/doc/manuals/r-devel/NEWS.html

Would it be possible to update the code to work with the newer R versions?

Thank you in advance.

**Comment by KarstensLab** [comment]
Thank you for letting us know about this issue. We are looking into resolving it and will post when there is a fix.

**Comment by sterrettJD** [comment]
We also recently ran into this issue in our group. I think I have a fix in [my branch](https://github.com/sterrettJD/microshades/tree/fix_length_coercion) that has worked for us. 

Effectively, the new R update causes these if statements on vectors longer than 1 `if( c(F, F, F, T) || c(F, F, F, F) )` to break, which is because the user hasn't explicitly specified how the `if` should be satisfied across the 4 elements in each vector. 2 main options are: 
- **all** positions being `TRUE` (element-wise, so `c(T, T, T, F) || c(F, F, F, T)` should satisfy the `or` operator at all elements in the vectors, but `c(F, F, F, F) || c(F, F, F, T)`  would not satisfy it)
- **any** positions being `TRUE` (`c(F, F, F, F) || c(F, F, F, T)` would satisfy this)

I used `sum()` to capture the **any** scenario, which I believe is what the original functionality did.

@sarmol I am opening a pull request now, but you should be able to use my branch in the meantime. You can run `remotes::install_github("sterrettJD/microshades@fix_length_coercion", dependencies=TRUE)` then detach and reload the microshades library if you already have it loaded into your environment.

**Comment by lakarstens** [comment]
We reviewed and committed @sterrettJD's pull request to fix this issue.

**Comment by sarmol** [comment]
Thank you @sterrettJD and @lakarstens for fixing it!
